version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: task_management_mysql
    restart: unless-stopped
    ports:
      - "3380:3306"
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_admin
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task_management_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: task_management_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task_management_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: task_management_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - task_management_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: task_management
      DB_USERNAME: user_admin
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      QUEUE_CONNECTION: redis
      REDIS_QUEUE: task_management_queue
      REDIS_QUEUE_CONNECTION: default
      REDIS_QUEUE_RETRY_AFTER: 90
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM_ADDRESS: "noreply@taskmanagement.local"
      MAIL_FROM_NAME: "Task Management"
      APP_ENV: local
      APP_DEBUG: "true"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - task_management_network

networks:
  task_management_network:
    driver: bridge
    ipam:
        config:
            - subnet: 192.168.124.0/24

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
